//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC42014.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public string invoice_serial { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> source_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> owner_id { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
