//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC42014.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> paid_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
