//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC42014.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order_Details = new HashSet<Order_Details>();
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<int> instock { get; set; }
        public Nullable<int> outstock { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public string meta_options { get; set; }
        public string city { get; set; }
        public string photo { get; set; }
    
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
